import re

ALL_COUNTRY_NATIONALITY_TH = {
    "AFGHAN": "อัฟกัน",
    "ALBANIAN": "แอลเบเนีย",
    "ALGERIAN": "แอลจีเรีย",
    "ANDORRAN": "อันดอร์รา",
    "ANGOLAN": "แองโกลา",
    "ARGENTINE": "อาร์เจนตินา",
    "ARMENIAN": "อาร์เมเนีย",
    "AUSTRALIAN": "ออสเตรเลีย",
    "AUSTRIAN": "ออสเตรีย",
    "AZERBAIJANI": "อาเซอร์ไบจาน",
    "BAHAMIAN": "บาฮามาส",
    "BAHRAINI": "บาห์เรน",
    "BANGLADESHI": "บังกลาเทศ",
    "BARBADIAN": "บาร์เบโดส",
    "BELARUSIAN": "เบลารุส",
    "BELGIAN": "เบลเยียม",
    "BELIZEAN": "เบลีซ",
    "BENINESE": "เบนิน",
    "BHUTANESE": "ภูฏาน",
    "BOLIVIAN": "โบลิเวีย",
    "MOTSWANA": "บอตสวานา",
    "BRAZILIAN": "บราซิล",
    "BRUNEIAN": "บรูไน",
    "BULGARIAN": "บัลแกเรีย",
    "CAMBODIAN": "กัมพูชา",
    "CAMEROONIAN": "แคเมอรูน",
    "CANADIAN": "แคนาดา",
    "CHILEAN": "ชิลี",
    "CHINESE": "จีน",
    "COLOMBIAN": "โคลอมเบีย",
    "COSTA RICAN": "คอสตาริกา",
    "CROATIAN": "โครเอเชีย",
    "CUBAN": "คิวบา",
    "CYPRIOT": "ไซปรัส",
    "CZECH": "เช็ก",
    "DANISH": "เดนมาร์ก",
    "DOMINICAN": "โดมินิกัน",
    "ECUADORIAN": "เอกวาดอร์",
    "EGYPTIAN": "อียิปต์",
    "SALVADORAN": "เอลซัลวาดอร์",
    "ESTONIAN": "เอสโตเนีย",
    "ETHIOPIAN": "เอธิโอเปีย",
    "FIJIAN": "ฟิจิ",
    "FINNISH": "ฟินแลนด์",
    "FRENCH": "ฝรั่งเศส",
    "GABONESE": "กาบอง",
    "GAMBIAN": "แกมเบีย",
    "GEORGIAN": "จอร์เจีย",
    "GERMAN": "เยอรมนี",
    "GHANAIAN": "กานา",
    "GREEK": "กรีซ",
    "GRENADIAN": "เกรเนดา",
    "GUATEMALAN": "กัวเตมาลา",
    "GUINEAN": "กินี",
    "HAITIAN": "เฮติ",
    "HONDURAN": "ฮอนดูรัส",
    "HUNGARIAN": "ฮังการี",
    "ICELANDIC": "ไอซ์แลนด์",
    "INDIAN": "อินเดีย",
    "INDONESIAN": "อินโดนีเซีย",
    "IRANIAN": "อิหร่าน",
    "IRAQI": "อิรัก",
    "IRISH": "ไอร์แลนด์",
    "ISRAELI": "อิสราเอล",
    "ITALIAN": "อิตาลี",
    "JAPANESE": "ญี่ปุ่น",
    "KENYAN": "เคนยา",
    "KOREAN": "เกาหลีใต้",
    "KUWAITI": "คูเวต",
    "LAO": "ลาว",
    "LATVIAN": "ลัตเวีย",
    "LEBANESE": "เลบานอน",
    "LIBERIAN": "ไลบีเรีย",
    "LIBYAN": "ลิเบีย",
    "LITHUANIAN": "ลิทัวเนีย",
    "LUXEMBOURGISH": "ลักเซมเบิร์ก",
    "MALAYSIAN": "มาเลเซีย",
    "MALDIVIAN": "มัลดีฟส์",
    "MALIAN": "มาลี",
    "MALTESE": "มอลตา",
    "MEXICAN": "เม็กซิโก",
    "MOLDOVAN": "มอลโดวา",
    "MONEGASQUE": "โมนาโก",
    "MONGOLIAN": "มองโกเลีย",
    "MONTENEGRIN": "มอนเตเนโกร",
    "MOROCCAN": "โมร็อกโก",
    "MOZAMBICAN": "โมซัมบิก",
    "BURMESE": "เมียนมา",
    "NEPALESE": "เนปาล",
    "DUTCH": "เนเธอร์แลนด์",
    "NEW ZEALANDER": "นิวซีแลนด์",
    "NICARAGUAN": "นิการากัว",
    "NIGERIAN": "ไนจีเรีย",
    "MACEDONIAN": "นอร์ทมาซิโดเนีย",
    "NORWEGIAN": "นอร์เวย์",
    "OMANI": "โอมาน",
    "PAKISTANI": "ปากีสถาน",
    "PANAMANIAN": "ปานามา",
    "PARAGUAYAN": "ปารากวัย",
    "PERUVIAN": "เปรู",
    "FILIPINO": "ฟิลิปปินส์",
    "POLISH": "โปแลนด์",
    "PORTUGUESE": "โปรตุเกส",
    "QATARI": "กาตาร์",
    "ROMANIAN": "โรมาเนีย",
    "RUSSIAN": "รัสเซีย",
    "SAUDI ARABIAN": "ซาอุดีอาระเบีย",
    "SENEGALESE": "เซเนกัล",
    "SINGAPOREAN": "สิงคโปร์",
    "SLOVAK": "สโลวาเกีย",
    "SLOVENIAN": "สโลวีเนีย",
    "SOUTH AFRICAN": "แอฟริกาใต้",
    "SPANISH": "สเปน",
    "SRI LANKAN": "ศรีลังกา",
    "SWEDISH": "สวีเดน",
    "SWISS": "สวิตเซอร์แลนด์",
    "SYRIAN": "ซีเรีย",
    "TAIWANESE": "ไต้หวัน",
    "TANZANIAN": "แทนซาเนีย",
    "THAI": "ไทย",
    "TOGOLESE": "โตโก",
    "TRINIDADIAN": "ตรินิแดดและโตเบโก",
    "TUNISIAN": "ตูนิเซีย",
    "TURKISH": "ตุรกี",
    "UGANDAN": "ยูกันดา",
    "UKRAINIAN": "ยูเครน",
    "EMIRATI": "สหรัฐอาหรับเอมิเรตส์",
    "BRITISH": "สหราชอาณาจักร",
    "AMERICAN": "สหรัฐอเมริกา",
    "URUGUAYAN": "อุรุกวัย",
    "VENEZUELAN": "เวเนซุเอลา",
    "VIETNAMESE": "เวียดนาม",
    "YEMENI": "เยเมน",
    "ZAMBIAN": "แซมเบีย",
    "ZIMBABWEAN": "ซิมบับเว"
}

def check_nationality_th(text: str):
    if not isinstance(text, str):
        return "", False

    t = re.sub(r"^สัญชาติ\s*", "", text.strip())
    t = re.sub(r"\s+", " ", t)

    thai_values = {v.replace(" ", "") for v in ALL_COUNTRY_NATIONALITY_TH.values()}

    if t in thai_values:
        return t, True

    return t, False