ALL_COUNTRY_NATIONALITY = {
    "AFGHAN": "Afghanistan",
    "ALBANIAN": "Albania",
    "ALGERIAN": "Algeria",
    "ANDORRAN": "Andorra",
    "ANGOLAN": "Angola",
    "ARGENTINE": "Argentina",
    "ARMENIAN": "Armenia",
    "AUSTRALIAN": "Australia",
    "AUSTRIAN": "Austria",
    "AZERBAIJANI": "Azerbaijan",
    "BAHAMIAN": "Bahamas",
    "BAHRAINI": "Bahrain",
    "BANGLADESHI": "Bangladesh",
    "BARBADIAN": "Barbados",
    "BELARUSIAN": "Belarus",
    "BELGIAN": "Belgium",
    "BELIZEAN": "Belize",
    "BENINESE": "Benin",
    "BHUTANESE": "Bhutan",
    "BOLIVIAN": "Bolivia",
    "MOTSWANA": "Botswana",
    "BRAZILIAN": "Brazil",
    "BRUNEIAN": "Brunei",
    "BULGARIAN": "Bulgaria",
    "CAMBODIAN": "Cambodia",
    "CAMEROONIAN": "Cameroon",
    "CANADIAN": "Canada",
    "CHILEAN": "Chile",
    "CHINESE": "China",
    "COLOMBIAN": "Colombia",
    "COSTA RICAN": "Costa Rica",
    "CROATIAN": "Croatia",
    "CUBAN": "Cuba",
    "CYPRIOT": "Cyprus",
    "CZECH": "Czech Republic",
    "DANISH": "Denmark",
    "DOMINICAN": "Dominican Republic",
    "ECUADORIAN": "Ecuador",
    "EGYPTIAN": "Egypt",
    "SALVADORAN": "El Salvador",
    "ESTONIAN": "Estonia",
    "ETHIOPIAN": "Ethiopia",
    "FIJIAN": "Fiji",
    "FINNISH": "Finland",
    "FRENCH": "France",
    "GABONESE": "Gabon",
    "GAMBIAN": "Gambia",
    "GEORGIAN": "Georgia",
    "GERMAN": "Germany",
    "GHANAIAN": "Ghana",
    "GREEK": "Greece",
    "GRENADIAN": "Grenada",
    "GUATEMALAN": "Guatemala",
    "GUINEAN": "Guinea",
    "HAITIAN": "Haiti",
    "HONDURAN": "Honduras",
    "HUNGARIAN": "Hungary",
    "ICELANDIC": "Iceland",
    "INDIAN": "India",
    "INDONESIAN": "Indonesia",
    "IRANIAN": "Iran",
    "IRAQI": "Iraq",
    "IRISH": "Ireland",
    "ISRAELI": "Israel",
    "ITALIAN": "Italy",
    "JAPANESE": "Japan",
    "KENYAN": "Kenya",
    "KOREAN": "Korea, South",
    "KUWAITI": "Kuwait",
    "LAO": "Laos",
    "LATVIAN": "Latvia",
    "LEBANESE": "Lebanon",
    "LIBERIAN": "Liberia",
    "LIBYAN": "Libya",
    "LITHUANIAN": "Lithuania",
    "LUXEMBOURGISH": "Luxembourg",
    "MALAYSIAN": "Malaysia",
    "MALDIVIAN": "Maldives",
    "MALIAN": "Mali",
    "MALTESE": "Malta",
    "MEXICAN": "Mexico",
    "MOLDOVAN": "Moldova",
    "MONEGASQUE": "Monaco",
    "MONGOLIAN": "Mongolia",
    "MONTENEGRIN": "Montenegro",
    "MOROCCAN": "Morocco",
    "MOZAMBICAN": "Mozambique",
    "BURMESE": "Myanmar",
    "NEPALESE": "Nepal",
    "DUTCH": "Netherlands",
    "NEW ZEALANDER": "New Zealand",
    "NICARAGUAN": "Nicaragua",
    "NIGERIAN": "Nigeria",
    "MACEDONIAN": "North Macedonia",
    "NORWEGIAN": "Norway",
    "OMANI": "Oman",
    "PAKISTANI": "Pakistan",
    "PANAMANIAN": "Panama",
    "PARAGUAYAN": "Paraguay",
    "PERUVIAN": "Peru",
    "FILIPINO": "Philippines",
    "POLISH": "Poland",
    "PORTUGUESE": "Portugal",
    "QATARI": "Qatar",
    "ROMANIAN": "Romania",
    "RUSSIAN": "Russia",
    "SAUDI ARABIAN": "Saudi Arabia",
    "SENEGALESE": "Senegal",
    "SINGAPOREAN": "Singapore",
    "SLOVAK": "Slovakia",
    "SLOVENIAN": "Slovenia",
    "SOUTH AFRICAN": "South Africa",
    "SPANISH": "Spain",
    "SRI LANKAN": "Sri Lanka",
    "SWEDISH": "Sweden",
    "SWISS": "Switzerland",
    "SYRIAN": "Syria",
    "TAIWANESE": "Taiwan",
    "TANZANIAN": "Tanzania",
    "THAI": "Thailand",
    "TOGOLESE": "Togo",
    "TRINIDADIAN": "Trinidad and Tobago",
    "TUNISIAN": "Tunisia",
    "TURKISH": "Turkey",
    "UGANDAN": "Uganda",
    "UKRAINIAN": "Ukraine",
    "EMIRATI": "United Arab Emirates",
    "BRITISH": "United Kingdom",
    "AMERICAN": "United States",
    "URUGUAYAN": "Uruguay",
    "VENEZUELAN": "Venezuela",
    "VIETNAMESE": "Vietnam",
    "YEMENI": "Yemen",
    "ZAMBIAN": "Zambia",
    "ZIMBABWEAN": "Zimbabwe"
}

def check_nationality(text: str):
    if not isinstance(text, str):
        return "", False

    # Normalize
    t = text.upper()
    t = t.replace(" ", "").replace(".", "")

    if t in ALL_COUNTRY_NATIONALITY:
        return t, True

    return t, False
